// src/services/adminTableRegistry.js

export const ADMIN_TABLES = {
  employee_announcements: {
    label: "Employee Announcements",
    collection: "employee_announcements",
    columns: ["title", "message", "audience", "priority", "createdAt", "updatedAt"],
    sortableBy: ["title", "createdAt", "updatedAt"],
    searchableFields: ["title", "message", "audience", "priority"],
    canCreate: true,
    canEdit: true,
    canDelete: true,
    readOnly: false,
    hiddenFields: [],
  },

  employee_profiles: {
    label: "Employee Profiles",
    collection: "employee_profiles",
    columns: ["employeeId", "name", "email", "department", "role", "status", "updatedAt"],
    sortableBy: ["name", "employeeId", "department", "updatedAt"],
    searchableFields: ["employeeId", "name", "email", "department", "role", "status"],
    canCreate: true,
    canEdit: true,
    canDelete: false,
    readOnly: false,
    hiddenFields: [],
  },

  portal_user_requests: {
    label: "Portal User Requests",
    collection: "portal_user_requests",
    columns: ["name", "email", "employeeId", "status", "createdAt", "updatedAt"],
    sortableBy: ["status", "createdAt", "updatedAt"],
    searchableFields: ["name", "email", "employeeId", "status"],
    canCreate: false,
    canEdit: true,
    canDelete: false,
    readOnly: false,
    hiddenFields: [],
  },

  break_notifications: {
    label: "Break Notifications",
    collection: "break_notifications",
    columns: ["userId", "name", "type", "status", "createdAt"],
    sortableBy: ["createdAt", "status"],
    searchableFields: ["userId", "name", "type", "status"],
    canCreate: true,
    canEdit: true,
    canDelete: true,
    readOnly: false,
    hiddenFields: [],
  },

  over_break_notes: {
    label: "Over Break Notes",
    collection: "over_break_notes",
    columns: ["userId", "employeeId", "note", "status", "createdAt"],
    sortableBy: ["createdAt", "status"],
    searchableFields: ["userId", "employeeId", "note", "status"],
    canCreate: true,
    canEdit: true,
    canDelete: true,
    readOnly: false,
    hiddenFields: [],
  },

  employeeAssignments: {
    label: "Employee Assignments",
    collection: "employeeAssignments",
    columns: ["title", "employeeUserId", "status", "deadlineDate", "updatedAt"],
    sortableBy: ["title", "status", "deadlineDate", "updatedAt"],
    searchableFields: ["title", "employeeUserId", "status"],
    canCreate: true,
    canEdit: true,
    canDelete: true,
    readOnly: false,
    hiddenFields: [],
  },

  break_logs: {
    label: "Break Logs",
    collection: "break_logs",
    columns: ["userId", "name", "breakType", "startTime", "endTime", "status"],
    sortableBy: ["startTime", "endTime", "status"],
    searchableFields: ["userId", "name", "breakType", "status"],
    canCreate: false,
    canEdit: false,
    canDelete: false,
    readOnly: true,
    hiddenFields: [],
  },

  portal_active_sessions: {
    label: "Portal Active Sessions",
    collection: "portal_active_sessions",
    columns: ["userId", "email", "role", "createdAt", "lastSeenAt"],
    sortableBy: ["createdAt", "lastSeenAt"],
    searchableFields: ["userId", "email", "role"],
    canCreate: false,
    canEdit: false,
    canDelete: true,
    readOnly: true,
    hiddenFields: [],
  },

  users: {
    label: "Users",
    collection: "users",
    columns: ["userId", "employeeId", "name", "email", "role", "isActive", "updatedAt"],
    sortableBy: ["name", "email", "role", "updatedAt"],
    searchableFields: ["userId", "employeeId", "name", "email", "role"],
    canCreate: false,
    canEdit: true,
    canDelete: false,
    readOnly: false,
    hiddenFields: [
      "portalPasswordHash",
      "portalPasswordSalt",
      "passwordHash",
      "passwordSalt",
      "tokens",
      "secret",
    ],
  },

  user_permissions: {
    label: "User Permissions",
    collection: "user_permissions",
    columns: ["userId", "role", "permissions", "updatedAt"],
    sortableBy: ["role", "updatedAt"],
    searchableFields: ["userId", "role"],
    canCreate: false,
    canEdit: true,
    canDelete: false,
    readOnly: false,
    hiddenFields: [],
  },

  employee_credentials: {
    label: "Employee Credentials",
    collection: "employee_credentials",
    columns: ["employeeId", "name", "email", "createdAt"],
    sortableBy: ["employeeId", "name", "createdAt"],
    searchableFields: ["employeeId", "name", "email"],
    canCreate: false,
    canEdit: false,
    canDelete: false,
    readOnly: true,
    hiddenFields: [
      "password",
      "passwordHash",
      "passwordSalt",
      "secret",
      "token",
      "accessToken",
      "refreshToken",
      "apiKey",
    ],
    excluded: true,
  },

  hyacinth_api_cache: {
    label: "Hyacinth API Cache",
    collection: "hyacinth_api_cache",
    columns: ["key", "createdAt", "updatedAt"],
    sortableBy: ["createdAt", "updatedAt"],
    searchableFields: ["key"],
    canCreate: false,
    canEdit: false,
    canDelete: true,
    readOnly: true,
    hiddenFields: ["payload", "raw", "response"],
    excluded: true,
  },
};